const mockData = {
  patients: [
    {
      id: 0,
      name: "Andrew Nelson",
      age: 41,
      gender: "male",
      blood_type: "O+",
      address: "1818 Elm Road, Valleyview, USA",
      phone: "555-5566",
      email: "andrew.nelson@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 1,
      name: "Sophia Miller",
      age: 32,
      gender: "female",
      blood_type: "A-",
      address: "222 Birch Lane, Lakeside, USA",
      phone: "555-7788",
      email: "sophia.miller@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 2,
      name: "Ethan Davis",
      age: 45,
      gender: "male",
      blood_type: "B+",
      address: "333 Pine Road, Meadowbrook, USA",
      phone: "555-9900",
      email: "ethan.davis@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 3,
      name: "Emma White",
      age: 28,
      gender: "female",
      blood_type: "AB-",
      address: "444 Cedar Drive, Oakville, USA",
      phone: "555-1122",
      email: "emma.white@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 4,
      name: "Daniel Smith",
      age: 39,
      gender: "male",
      blood_type: "O-",
      address: "555 Elm Lane, Ridgeway, USA",
      phone: "555-3344",
      email: "daniel.smith@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 5,
      name: "Olivia Turner",
      age: 33,
      gender: "female",
      blood_type: "A+",
      address: "666 Oak Road, Valleyview, USA",
      phone: "555-5566",
      email: "olivia.turner@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 6,
      name: "Liam Adams",
      age: 50,
      gender: "male",
      blood_type: "B-",
      address: "777 Cedar Lane, Cityville, USA",
      phone: "555-7788",
      email: "liam.adams@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 7,
      name: "Ava Hall",
      age: 27,
      gender: "female",
      blood_type: "AB+",
      address: "888 Pine Avenue, Hamlet, USA",
      phone: "555-9900",
      email: "ava.hall@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 8,
      name: "Noah Johnson",
      age: 42,
      gender: "male",
      blood_type: "O+",
      address: "999 Birch Road, Newtown, USA",
      phone: "555-1122",
      email: "noah.johnson@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 9,
      name: "Isabella Brown",
      age: 29,
      gender: "female",
      blood_type: "A-",
      address: "1010 Elm Drive, Brookside, USA",
      phone: "555-3344",
      email: "isabella.brown@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 10,
      name: "Mason Turner",
      age: 37,
      gender: "male",
      blood_type: "B+",
      address: "1111 Oak Avenue, Othercity, USA",
      phone: "555-5566",
      email: "mason.turner@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 11,
      name: "Sophia Taylor",
      age: 31,
      gender: "female",
      blood_type: "AB-",
      address: "1212 Birch Road, Riverside, USA",
      phone: "555-7788",
      email: "sophia.taylor@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 12,
      name: "Logan Harris",
      age: 46,
      gender: "male",
      blood_type: "O+",
      address: "1313 Pine Lane, Crestview, USA",
      phone: "555-9900",
      email: "logan.harris@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 13,
      name: "Amelia Miller",
      age: 24,
      gender: "female",
      blood_type: "A+",
      address: "1414 Cedar Lane, Villagetown, USA",
      phone: "555-1122",
      email: "amelia.miller@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 14,
      name: "Elijah Turner",
      age: 43,
      gender: "male",
      blood_type: "B-",
      address: "1515 Elm Road, Valleyview, USA",
      phone: "555-3344",
      email: "elijah.turner@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 15,
      name: "Mia Walker",
      age: 30,
      gender: "female",
      blood_type: "AB+",
      address: "1616 Oak Lane, Ridgeway, USA",
      phone: "555-5566",
      email: "mia.walker@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 16,
      name: "Jackson Adams",
      age: 48,
      gender: "male",
      blood_type: "O-",
      address: "1717 Pine Road, Meadowbrook, USA",
      phone: "555-7788",
      email: "jackson.adams@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 17,
      name: "Aria Nelson",
      age: 26,
      gender: "female",
      blood_type: "A+",
      address: "1818 Cedar Drive, Oakville, USA",
      phone: "555-9900",
      email: "aria.nelson@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 18,
      name: "Caleb Brown",
      age: 39,
      gender: "male",
      blood_type: "B+",
      address: "1919 Elm Lane, Ridgeway, USA",
      phone: "555-1122",
      email: "caleb.brown@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 19,
      name: "Scarlett Hall",
      age: 29,
      gender: "female",
      blood_type: "AB-",
      address: "2020 Birch Road, Newtown, USA",
      phone: "555-3344",
      email: "scarlett.hall@example.com",
      image: "/assets/F062_|Radius_CL.png",
    },
    {
      id: 20,
      name: "Lucas Turner",
      age: 42,
      gender: "male",
      blood_type: "O+",
      address: "2121 Oak Avenue, Othercity, USA",
      phone: "555-5566",
      email: "lucas.turner@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 21,
      name: "Lily Taylor",
      age: 31,
      gender: "female",
      blood_type: "A-",
      address: "2222 Elm Road, Valleyview, USA",
      phone: "555-7788",
      email: "lily.taylor@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 22,
      name: "Gabriel Harris",
      age: 47,
      gender: "male",
      blood_type: "B-",
      address: "2323 Cedar Lane, Cityville, USA",
      phone: "555-9900",
      email: "gabriel.harris@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 23,
      name: "Chloe Smith",
      age: 28,
      gender: "female",
      blood_type: "AB+",
      address: "2424 Pine Drive, Oakville, USA",
      phone: "555-1122",
      email: "chloe.smith@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 24,
      name: "Henry Turner",
      age: 37,
      gender: "male",
      blood_type: "O+",
      address: "2525 Birch Lane, Lakeside, USA",
      phone: "555-3344",
      email: "henry.turner@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 25,
      name: "Avery Miller",
      age: 30,
      gender: "female",
      blood_type: "A+",
      address: "2626 Oak Road, Valleyview, USA",
      phone: "555-5566",
      email: "avery.miller@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 26,
      name: "Elijah Adams",
      age: 44,
      gender: "male",
      blood_type: "B+",
      address: "2727 Cedar Drive, Oakville, USA",
      phone: "555-7788",
      email: "elijah.adams@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
    {
      id: 27,
      name: "Eva Nelson",
      age: 25,
      gender: "female",
      blood_type: "AB-",
      address: "2828 Pine Lane, Crestview, USA",
      phone: "555-9900",
      email: "eva.nelson@example.com",
      image: "/assets/F040_Radius_CL.png",
    },
    {
      id: 28,
      name: "Carter White",
      age: 35,
      gender: "male",
      blood_type: "O-",
      address: "2929 Elm Avenue, Hamlet, USA",
      phone: "555-1122",
      email: "carter.white@example.com",
      image: "/assets/F062_Radius_CL.png",
    },
    {
      id: 29,
      name: "Zoe Turner",
      age: 29,
      gender: "female",
      blood_type: "A+",
      address: "3030 Cedar Road, Lakeside, USA",
      phone: "555-3344",
      email: "zoe.turner@example.com",
      image: "/assets/F055_Radius_CL.png",
    },
  ],
};

export default mockData;
